### ISSUE TITLE
Error when @covers class<extended> and class does not exist

### ISSUE THREAD

**Issue by willemstuursma** [oradwell/covers-validator#5]
Hi @ockcyp. 

I am getting an error, when the invalid `@covers` annotation has a class and the annotation is to cover parent classes as wel:

`* @covers Model_OAuth2_Application<extended>`

This gives the following error if the class does not exist:

```
     [exec]   [ErrorException]                                                                           
     [exec]   class_implements(): Class Model_OAuth2_Application does not exist and could not be loaded  
     [exec]                                                                                              
     [exec] 
     [exec] 
     [exec] validate [-c|--configuration CONFIGURATION] [--bootstrap BOOTSTRAP]
```

Probably something internal in PHPUnit again?

**Comment by ockcyp** [comment]
So it works when you remove ``<extended>``? Strange. I will have a look.

**Comment by ockcyp** [comment]
Yes it is from PHPUnit internals. [phpunit Util/Test.php#L995](https://github.com/sebastianbergmann/phpunit/blob/master/src/Util/Test.php#L995)
It's not checking whether the class exists. I guess your PHP configuration throws ``ErrorException`` instead of giving a warning unlike mine:
```
PHP Warning:  class_implements(): Class NonExistingClass does not exist and could not be loaded in /path/to/vendor/phpunit/phpunit/src/Util/Test.php on line 978
PHP Warning:  class_parents(): Class NonExistingClass does not exist and could not be loaded in /path/to/vendor/phpunit/phpunit/src/Util/Test.php on line 979
```

I want to try to avoid parsing the ``@covers`` tags in order to have the same behaviour as the PHPUnit used in the project. I will try to make a PR to PHPUnit for this.

**Comment by willemstuursma** [comment]
Thanks, I really appreciate it.

**Comment by oradwell** [comment]
according to https://github.com/sebastianbergmann/phpunit/pull/1971 this is not an issue anymore
